tasks:
  - name: installation
    command: |
      cd backend
      pip install -r requirements.txt
      pip install -r dev_requirements.txt
      gp sync-done install-backend
      cd ../frontend
      npm install
      gp sync-done install-frontend
  - name: uvicorn
    command: |
      gp sync-await install-backend
      cd backend
      uvicorn app.main:app --port 8001 --log-config=log-config.yaml --reload
  - name: celery worker
    command: |
      gp sync-await install-backend
      cd backend
      celery -A app.worker worker -l info -Q ytta-celery
    openMode: split-right
  - name: vue
    command: |
      gp sync-await install-frontend
      cd frontend
      npm run serve
    openMode: split-right

ports:
  - port: 8001
    onOpen: open-preview
    visibility: public
  - port: 8080
    onOpen: open-browser
