tasks:
  - command: |
      pip install -r requirements.txt
      pip install -r dev_requirements.txt
      gp sync-done install
  - name: uvicorn
    command: |
      gp sync-await install
      uvicorn app.main:app --port 8001 --log-config=log-config.yaml --reload

ports:
  - port: 8001
    onOpen: open-preview
