"""adding to video model

Revision ID: 0fc682e94c70
Revises: d4867f3a4c0a
Create Date: 2022-03-18 13:39:19.875763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc682e94c70'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('video', sa.Column('yt_id', sa.String(), nullable=True))
    op.add_column('video', sa.Column('url', sa.String(), nullable=True))
    op.create_index(op.f('ix_video_url'), 'video', ['url'], unique=False)
    op.create_index(op.f('ix_video_yt_id'), 'video', ['yt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_yt_id'), table_name='video')
    op.drop_index(op.f('ix_video_url'), table_name='video')
    op.drop_column('video', 'url')
    op.drop_column('video', 'yt_id')
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
