"""cascade delete label_occurances from video deletion

Revision ID: 1331a020ef26
Revises: 579d3bd520a2
Create Date: 2022-04-14 13:08:06.786238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1331a020ef26'
down_revision = '579d3bd520a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('labeloccurance', 'label_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('labeloccurance', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('labeloccurance', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('labeloccurance', 'label_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
