"""cascade delete label_occurances from video deletion

Revision ID: 1d99e5f9be80
Revises: beb23bab18be
Create Date: 2022-04-14 13:04:54.269122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d99e5f9be80'
down_revision = 'beb23bab18be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('labeloccurance_label_id_fkey', 'labeloccurance', type_='foreignkey')
    op.create_foreign_key(None, 'labeloccurance', 'label', ['label_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labeloccurance', type_='foreignkey')
    op.create_foreign_key('labeloccurance_label_id_fkey', 'labeloccurance', 'label', ['label_id'], ['id'])
    # ### end Alembic commands ###
