"""cascade delete label_occurances from video deletion

Revision ID: 579d3bd520a2
Revises: 1d99e5f9be80
Create Date: 2022-04-14 13:06:32.292739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579d3bd520a2'
down_revision = '1d99e5f9be80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('labeloccurance_video_id_fkey', 'labeloccurance', type_='foreignkey')
    op.drop_constraint('labeloccurance_label_id_fkey', 'labeloccurance', type_='foreignkey')
    op.create_foreign_key(None, 'labeloccurance', 'video', ['video_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'labeloccurance', 'label', ['label_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labeloccurance', type_='foreignkey')
    op.drop_constraint(None, 'labeloccurance', type_='foreignkey')
    op.create_foreign_key('labeloccurance_label_id_fkey', 'labeloccurance', 'label', ['label_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('labeloccurance_video_id_fkey', 'labeloccurance', 'video', ['video_id'], ['id'])
    # ### end Alembic commands ###
