"""Added uniqueness constraint

Revision ID: b3c4246fd2a9
Revises: 0fc682e94c70
Create Date: 2022-03-23 13:00:51.780522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c4246fd2a9'
down_revision = '0fc682e94c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_owner_video_uc', 'video', ['owner_id', 'yt_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_owner_video_uc', 'video', type_='unique')
    # ### end Alembic commands ###
