"""adding status to video model

Revision ID: f74c84c4bff8
Revises: b3c4246fd2a9
Create Date: 2022-04-07 12:53:19.548954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74c84c4bff8'
down_revision = 'b3c4246fd2a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'status')
    # ### end Alembic commands ###
